name: release-please

on:
  push:
    branches:
      - main
      - next
      
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: google-github-actions/release-please-action@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          monorepo-tags: true
        
      - name: Release next
        uses: google-github-actions/release-please-action@v3
        if: ${{ github.ref == 'refs/heads/next' }}
        with:
          monorepo-tags: true
          prerelease: true
          default-branch: next